### ISSUE TITLE
Nodejs 16 deprecation warnings

### ISSUE THREAD

**Issue by mnp** [replicatedhq/replicated-actions#53]
create_cluster

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: replicatedhq/compatibility-actions/create-cluster@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by jdewinne** [comment]
Resolved in [v1.13.1](https://github.com/replicatedhq/replicated-actions/releases/tag/v1.13.1)
